# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
# Achtung: da das image vom Server gelesen wird ist die Version vorgegeben !!!
name: Example add-on by SFeli
version: "1.2.0"
slug: example
description: Example add-on by SFeli
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
