# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# amd64: ghcr.io/hassio-addons/base:14.2.2
build_from:
  amd64: ghcr.io/hassio-addons/debian-base:6.2.0
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Homegear"
  org.opencontainers.image.description: "Homegear add-on to support MAX-Thermostate."
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
