name: "SF_Homegear"
version: "1.0.0"
slug: example
description: "Homegear Docker"
url: "https://github.com/SFeli/homegear/"
boot: "auto",
map: ["config:rw", "share:rw"],
ports: {
  "8080/tcp": 80,
  "2001/tcp": 2001,
  "2002/tcp": 2002,
  "2003/tcp": 2003
},
"environment": {    },
arch:
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
