name: "SF_Homegear"
version: test
slug: homegear
description: "Homegear - Test Version 8.x in Docker"
url: "https://github.com/SFeli/HA_Addons/homegear/"
webui: "[PROTO:http]://[HOST]:[PORT:8080]/admin"
startup: services
hassio_api: true
init: false
host_network: true
map: 
  - config:rw
  - share:rw
ports: 
  8080/tcp: 80
  2001/tcp: 2001
  2002/tcp: 2002
  2003/tcp: 2003
ports_description:
  8080/tcp: "Zugang"
environment: {}
arch:
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
