name: "SF_Homegear"
version: test
slug: homegear
description: "Homegear - Test Version 8.x in Docker"
url: "https://github.com/SFeli/HA_Addons/homegear/"
webui: "[PROTO:http]://[HOST]:[PORT:8080]/admin"
startup: services
hassio_api: true
init: false
host_network: true
map: 
  - config:rw
  - share:rw
ports: 
  - 8080/tcp: 80
  - 2001/tcp: 2001
  - 2002/tcp: 2002
  - 2003/tcp: 2003
ports_description:
  - 8080/tcp: "Homegear Web-Zugang"
  - 2001/tcp: "Homegear port 2001"
  - 2002/tcp: "Homegear port 2002"
  - 2003/tcp: "Homegear port 2003"
environment: {}
arch:
  - amd64
init: false
map:
  - share:rw
options:
  - message: "Hello world..."
  - homegear_user: "homegear"
  - homegear_usergroup: "homegear"
schema:
  - message: "str?"
  - homegear_user: "str"
  - homegear_usergroup: "str"
